name: Build

on: 
  workflow_call:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          set -eo pipefail
          xcodebuild -scheme ackee-ios-snapshots -destination 'generic/platform=iOS' build | xcbeautify